"use client";
import Image from "next/image";import type{ReactNode}from"react";import{mediaById}from"@/data/media";import type{Freshness,Stage,TripDay}from"@/data/product";import type{DayVisual}from"@/data/experience";
export function LandscapePhotoBlock({source,alt,priority=false,className=""}:{source:string;alt?:string;priority?:boolean;className?:string}){const m=mediaById.get(source);return m?<figure className={`landscape-photo ${className}`}><Image src={m.src} alt={alt||m.alt} fill sizes="(max-width:600px) 100vw,560px" priority={priority} unoptimized/></figure>:<figure className={`landscape-photo ${className}`}><img src={source} alt={alt||"北疆旅行环境"} loading={priority?"eager":"lazy"}/></figure>}
export function EditorialSection({eyebrow,title,action,children,className=""}:{eyebrow?:string;title:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`editorial-section ${className}`}><header><div>{eyebrow&&<small>{eyebrow}</small>}<h2>{title}</h2></div>{action}</header>{children}</section>}
export function DayHero({day,visual,weather,close}:{day:TripDay;visual:DayVisual;weather:ReactNode;close:()=>void}){return <section className="journal-hero"><header><button onClick={close}>← 行程</button><span>{String(day.day).padStart(2,"0")} / 07</span><time>SEP.{day.date.slice(3)}</time></header><div className="journal-hero-track"><LandscapePhotoBlock source={visual.hero} priority/><LandscapePhotoBlock source={visual.secondary}/></div><div className="journal-route"><small>DAY {String(day.day).padStart(2,"0")} · {day.date}</small><h1>{day.route.join(" → ")}</h1><p>{[day.distance,day.drive,day.sleep!=="—"?`住 ${day.sleep}`:"返程"].filter(Boolean).join("　·　")}</p></div><div className="journal-weather">{weather}</div></section>}
export function InfoRail({day,visual,confirmLabel,openMap,openConfirm}:{day:TripDay;visual:DayVisual;confirmLabel?:string;openMap:()=>void;openConfirm:()=>void}){return <section className="info-rail"><button onClick={openMap}><small>ROUTE</small><b>{day.drive||"自由安排"}</b><span>{day.distance||"市内"}</span></button><div><small>ALTITUDE</small><b>{visual.altitude}</b><span>{day.route.at(-1)}</span></div><button onClick={openConfirm}><small>CHECK</small><b>{confirmLabel||"无紧急确认"}</b><span>{confirmLabel?"查看状态":"稳定信息"}</span></button></section>}
export function Timeline({stages,openStage}:{stages:Stage[];openStage:(s:Stage)=>void}){return <div className="journal-timeline">{stages.map((s,i)=><button key={s.id} onClick={()=>openStage(s)}><time>{s.meta||String(i+1).padStart(2,"0")}</time><i/><span><small>{s.kind==="depart"?"出发前":s.kind==="travel"?"路上":s.kind==="arrival"?"抵达":s.kind==="evening"?"晚间":s.kind==="prepare"?"准备":"停留"}</small><b>{s.title}</b><em>→</em></span></button>)}</div>}
export function MapSheet({day,close,openFull}:{day:TripDay;close:()=>void;openFull:()=>void}){return <div className="journal-overlay" onClick={close}><section className="journal-sheet" onClick={e=>e.stopPropagation()}><header><div><small>ROUTE / DAY {String(day.day).padStart(2,"0")}</small><h2>路线顺序</h2></div><button onClick={close}>×</button></header><ol className="route-sequence">{day.route.map((p,i)=><li key={`${p}-${i}`}><span>{String(i+1).padStart(2,"0")}</span><b>{p}</b></li>)}</ol><button className="sheet-action" onClick={openFull}>打开真实地图 ↗</button></section></div>}
export function OutfitPreview({visual,open}:{visual:DayVisual;open:()=>void}){return <button className="outfit-preview" onClick={open}><LandscapePhotoBlock source={visual.outfit} alt={visual.outfitAlt}/><span><small>WHAT TO WEAR</small><b>{visual.outfitCopy}</b><p>{visual.outfitNote}</p><em>查看完整穿搭 →</em></span></button>}
export function ChecklistPreview({items,values,open}:{items:DayVisual["dayBag"];values:Record<string,boolean>;open:()=>void}){const done=items.filter(([id])=>values[id]).length,required=items.filter(([id,,l])=>l==="required"&&!values[id]).length;return <button className="checklist-preview" onClick={open}><span><small>DAY BAG</small><b>{required?`${required} 件必带物品未完成`:"必带物品已完成"}</b></span><strong>{done}<i>/</i>{items.length}</strong></button>}
export function ExpandedChecklistPage({day,visual,values,toggle,back}:{day:TripDay;visual:DayVisual;values:Record<string,boolean>;toggle:(id:string)=>void;back:()=>void}){const done=visual.dayBag.filter(([id])=>values[id]).length;return <main className="expanded-journal"><header className="expanded-nav"><button onClick={back}>← DAY {String(day.day).padStart(2,"0")}</button><span>{day.date}</span></header><LandscapePhotoBlock source={visual.secondary} priority className="expanded-landscape"/><EditorialSection eyebrow={`DAY ${String(day.day).padStart(2,"0")} · ON YOU`} title="当天随身"><div className="checklist-progress"><strong>{done}/{visual.dayBag.length}</strong><i><span style={{width:`${done/visual.dayBag.length*100}%`}}/></i></div><div className="expanded-checks">{visual.dayBag.map(([id,label,level])=><button key={id} className={values[id]?"done":""} onClick={()=>toggle(id)}><i>{values[id]?"✓":""}</i><span>{label}</span><small>{level==="required"?"必带":level==="recommended"?"建议":"可选"}</small></button>)}</div></EditorialSection></main>}
export function ExpandedOutfitPage({day,visual,back}:{day:TripDay;visual:DayVisual;back:()=>void}){return <main className="expanded-journal"><header className="expanded-nav"><button onClick={back}>← DAY {String(day.day).padStart(2,"0")}</button><span>{day.date}</span></header><LandscapePhotoBlock source={visual.secondary} priority className="expanded-landscape"/><EditorialSection eyebrow="WHAT TO WEAR" title="今天怎么穿"><div className="outfit-expanded"><LandscapePhotoBlock source={visual.outfit} alt={visual.outfitAlt}/><div><h3>{visual.outfitCopy}</h3><p>{visual.outfitNote}</p><dl><div><dt>早上</dt><dd>完整穿好，保暖与防风层留在身边。</dd></div><div><dt>中午</dt><dd>升温后先脱外层，里面仍能单独穿。</dd></div><div><dt>鞋</dt><dd>以当天步行量和防滑为准。</dd></div></dl></div></div></EditorialSection></main>}
export function BottomNav({active,change,share}:{active:string;change:(v:"home"|"trip"|"map"|"inspire"|"pack")=>void;share?:()=>void}){const items=[["home","首页"],["trip","行程"],["map","地图"],["inspire","灵感"],["pack","准备"]]as const;return <nav className="journal-nav">{items.map(([id,l])=><button key={id} aria-current={active===id?"page":undefined} onClick={()=>change(id)}>{l}</button>)}{share&&<button className="share-dot" onClick={share}>↗</button>}</nav>}
export function FreshnessLabel({type}:{type:Freshness}){return <small className={`journal-fresh ${type}`}>{type==="stable"?"稳定信息":type==="before"?"出发前确认":"当天确认"}</small>}
